development: &default
  adapter: postgresql
  database: smh_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: <%= ENV.fetch("DB_POOL", 5) %>
  reaping_frequency: <%= ENV.fetch("DB_REAPING_FREQUENCY", 10) %>
  timeout: 5000

test:
  <<: *default
  database: smh_test

production: &deploy
  adapter: postgresql
  encoding: utf8
  min_messages: warning
  pool: <%= [ENV.fetch("MAX_THREADS", 5), ENV.fetch("DB_POOL", 5)].max %>
  timeout: 5000
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>

staging: *deploy